### ISSUE TITLE
ruby2_keywords error when running on Ruby 2.6

### ISSUE THREAD

**Issue by orien** [sds/mock_redis#202]
Error when requiring `mock_redis` v0.27.0 on Ruby 2.6:

```
NoMethodError: undefined method `ruby2_keywords' for MockRedis::GeospatialMethods:Module
/app/vendor/bundle/ruby/2.6.0/gems/mock_redis-0.27.0/lib/mock_redis/geospatial_methods.rb:15:in `<module:GeospatialMethods>'
/app/vendor/bundle/ruby/2.6.0/gems/mock_redis-0.27.0/lib/mock_redis/geospatial_methods.rb:2:in `<class:MockRedis>'
/app/vendor/bundle/ruby/2.6.0/gems/mock_redis-0.27.0/lib/mock_redis/geospatial_methods.rb:1:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
…
```

This seems related to the changes in #199.

**Comment by sds** [comment]
Fix released in [0.27.1](https://github.com/sds/mock_redis/releases/tag/v0.27.1).

**Comment by orien** [comment]
Thanks @sds. Unfortunately, this didn't solve the problem. The error still exists with version 0.27.1.

**Comment by orien** [comment]
To make `ruby2_keywords` available to downstream dependants, we'll need to specify it as a runtime dependency:

```diff
- s.add_development_dependency 'ruby2_keywords'
+ s.add_runtime_dependency 'ruby2_keywords'
```

Development dependencies are only used during the development of the gem.

**Comment by sds** [comment]
Released in [0.27.2](https://github.com/sds/mock_redis/releases/tag/v0.27.2)

**Comment by orien** [comment]
Thanks @sds. Unfortunately, the error still occurs on version 0.27.2.

I wonder if there's a missing require.

**Comment by lucascharlesz** [comment]
Same problem here
